version: '3.8'

services:
  seata-server:
    image: seataio/seata-server:2.0.0
    container_name: seata-server
    restart: always  # 异常重启
    ports:
      - "8091:8091"
      - "7091:7091"
    volumes:
      # 挂载自定义配置文件（覆盖容器默认配置）
      - /Users/niici/local/seata/config/application.yml:/seata-server/resources/application.yml
      # 挂载日志目录（宿主机可查看）
      - /Users/niici/local/seata/logs:/seata-server/logs
    networks:
      - seata-network 
      #- nacos_nacos-network

networks:
  seata-network:
    driver: bridge
  # nacos_nacos-network:
  #   external: true 