spring:
  application:
    name: seata-business
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 5d5d91ba-a655-497c-bbe5-f7fe9424a6ac
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: 5d5d91ba-a655-497c-bbe5-f7fe9424a6ac
        prefix: seata-account
        file-extension: yml
        # 禁用import check避免不必要的警告
        import-check:
          enabled: false
server:
  port: 11000
# 配置日志级别 -- 需要配置成debug
logging:
  level:
    com.niici.business: debug

seata:
  enabled: true
  application-id: seata-business
  tx-service-group: default_tx_group
  registry:
    type: file
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace: 5d5d91ba-a655-497c-bbe5-f7fe9424a6ac
#      group: SEATA_GROUP
#      application: seata-server
#      username: nacos
#      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 5d5d91ba-a655-497c-bbe5-f7fe9424a6ac
      group: SEATA_GROUP
      username: nacos
      password: nacos
      data-id: seata-client.properties

