spring:
  cloud:
    gateway:
      # 配置全局跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"  # 指定具体域名或 pattern 生产环境（需要携带 cookie 或 Authorization）
            # allowed-origins: "*"        # 与 credentials 不兼容
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true # 控制跨域请求时，浏览器是否允许携带凭证信息
      routes:
        # 定义order服务的路由规则
        - id: order-route
          # 路由目标：负载均衡到admin-service服务（结合Nacos注册中心）
          uri: lb://service-order
          # 断言规则：路径匹配 + IP白名单
          predicates:
            - Path=/api/order/**
          filters:
            # /api/order/xxx -> /xxx
            - RewritePath=/api/order/(?<segment>.*), /$\{segment}
            - AddResponseHeader=X-Request-Header-Test, gateway
            - OnceTokenRequestHeader=X-Token, Uuid
        # 定义product服务的路由规则
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*), /$\{segment}
        - id: user-route
          uri: https://cn.bing.com/
          predicates:
            - Path=/search
            - Query=q,haha
            # 短写法
            - Vip=user,niici
            # 长写法
#            - name: Vip
#              args:
#                param: user
#                value: niici
