spring:
  cloud:
    gateway:
      routes:
        # 定义order服务的路由规则
        - id: order-route
          # 路由目标：负载均衡到admin-service服务（结合Nacos注册中心）
          uri: lb://service-order
          # 断言规则：路径匹配 + IP白名单
          predicates:
            - Path=/api/order/**
          filters:
            # /api/order/xxx -> /xxx
            - RewritePath=/api/order/(?<segment>.*), /$\{segment}
        # 定义product服务的路由规则
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*), /$\{segment}
        - id: user-route
          uri: https://cn.bing.com/
          predicates:
            - Path=/search
            - Query=q,haha
            # 短写法
            - Vip=user,niici
            # 长写法
#            - name: Vip
#              args:
#                param: user
#                value: niici
