# ???????key ???? tx-service-group ???value ? seata-server ?????
service.vgroupMapping.default_tx_group=default
# file ????? seata-server ????????? ip:port??????????
service.default.grouplist=127.0.0.1:8091
# ?????????false=???????true=?? @GlobalTransactional ??
service.disableGlobalTransaction=false

# RM ????????????????
client.rm.lock.retryInterval=10
# RM ????????????????????????
client.rm.lock.retryTimes=30
# RM ????????true=???????????false=????
client.rm.lock.retryPolicyBranchRollbackOnConflict=true
# TM ??????????????
client.tm.commitRetryCount=5
# TM ??????????????
client.tm.rollbackRetryCount=5
# TM ???????????????????????
client.tm.defaultGlobalTransactionTimeout=60000